[tool.poetry]
name = "overcast-opml-parser"
version = "0.0.1"
description = "A parser for Overcast's extended format"
authors = [
    "James Hogkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
untangle = "^1.1.1"
click = "^8.0.3"
pydantic = "^2.10.3"
requests-xml = "^0.2.3"
loguru = "^0.7.2"

[tool.poetry.dev-dependencies]
pylint = "^3.3.1"
pytest = "^8.3.3"
mypy = "^1.13"
black = "^24.10.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.1"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "overcast-opml-parser"
description = "A parser for Overcast's extended format"
license = "MIT"
version = "0.0.1"
authors = [
    { name = "James Hogkinson", email = "james@terminaloutcomes.com" },
]
