[tool.poetry]
name = "overcast-opml-parser"
version = "0.0.1"
description = "A parser for Overcast's extended format"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
untangle = "^1.1.1"
click = "^8.0.3"
pydantic = "^2.1.0"
requests-xml = "^0.2.3"
loguru = "^0.7.2"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^7.0.1"
mypy = "^1.7"
black = "^23.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
